%YAML:1.0

#common parameters
imu_topic: "/vn100/imu"
#image_topic: "/camera/image_raw"
image_topic: "/camera/edge"

output_path: "/home/wangyu/catkin_ws/src/ETIO/Trajactory/"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration 
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 640
image_height: 512
projection_parameters:
   k2: -0.08496902872697064
   k3: 0.03187315864785345
   k4: -0.034049499657443305
   k5: 0.012130867665956748
   mu: 401.38451199748766
   mv: 401.29068549562913
   u0: 325.76732098280326
   v0: 242.8548782760497

estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
ex_calib_result_path: "/config/ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        

extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.0117855883573, -0.28647209614, 0.958016094875,
          -0.999874920295, 0.00672951329814, 0.0143128409567,
          -0.0105472116009, -0.958064951756, -0.286356953021]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0580204187327, 0.00509889122184, -0.0717831343626]
#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 10            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.046           # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 5.0e-3         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 4.8e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81       # gravity magnitude

# acc_n: 0.03337           # accelerometer measurement noise standard deviation. #0.2   0.04
# gyr_n: 7.0e-3         # gyroscope measurement noise standard deviation.     #0.05  0.004
# acc_w: 0.0004         # accelerometer bias random work noise standard deviation.  #0.02
# gyr_w: 4.8e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
# g_norm: 9.81       # gravity magnitude
# acc_n: 0.08          # accelerometer measurement noise standard deviation. #0.2   0.04
# gyr_n: 0.004         # gyroscope measurement noise standard deviation.     #0.05  0.004
# acc_w: 0.00004         # accelerometer bias random work noise standard deviation.  #0.02
# gyr_w: 2.0e-6       # gyroscope bias random work noise standard deviation.     #4.0e-5
#loop closure parameters
loop_closure: 0                    # start loop closure
fast_relocalization: 1             # useful in real-time and large project
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/wangyu/catkin_ws/src/ETIO/Trajactory/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0                          # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                      # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0              # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ