%YAML:1.0
---
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -7.0186656567881034e-03, -3.2086403022902099e-01,
       9.4709926218828244e-01, -9.9997519888345743e-01,
       1.6998565026018486e-03, -6.8346255099498987e-03,
       5.8305264678804036e-04, -9.4712374302044688e-01,
       -3.2086800316726949e-01 ]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 1.0771974566922672e-01, 5.4494724442269507e-03,
       -2.0594860077074392e-02 ]
