%YAML:1.0

#common parameters
imu_topic: "/imu/data"
#image_topic: "/camera/image_raw"
image_topic: "/camera/edge"

output_path: "/home/wangyu/catkin_ws/src/ETIO/Trajactory/"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 384
image_height: 288
distortion_parameters:
   k1: -0.37928016180803364
   k2: 0.25345967114099605
   p1: -0.0005847084591513314
   p2: -0.00010192891742480979
projection_parameters:
   fx: 386.9947285032803
   fy: 386.9020486508100
   cx: 189.31522480114646
   cy: 137.56218844645235

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
ex_calib_result_path: "/config/ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        


# extrinsicRotation: !!opencv-matrix
#    rows: 3
#    cols: 3
#    dt: d
#    data: [ -3.0773070280166959e-02, -2.9173047766024141e-02,
#        9.9910057122872920e-01, -9.9307252502686194e-01,
#        -1.1251487133442195e-01, -3.3872758455298579e-02,
#        1.1340184382233132e-01, -9.9322169580242237e-01,
#        -2.5508524164596702e-02 ]
# extrinsicTranslation: !!opencv-matrix
#    rows: 3
#    cols: 1
#    dt: d
#    data: [ -9.1375071363497179e-02, -4.4184140854747520e-02,
#        -1.0347536806516207e-01 ]
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.03661086, -0.01488073, 0.9992188, 
          -0.99925852, 0.01247088, -0.03642659,
          -0.01191909, -0.9998115, -0.01532627]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.05709379, -0.00499511, -0.03864174]
#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 15            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.1799864967545799e-02          # accelerometer measurement noise standard deviation. #0.2
gyr_n: 3.0500291741550676e-03         # gyroscope measurement noise standard deviation.     #0.05
acc_w: 1.6526770796823677e-04         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 5.4449462984119345e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.78       # gravity magnitude


#loop closure parameters
loop_closure: 0                    # start loop closure
fast_relocalization: 1             # useful in real-time and large project
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/wangyu/catkin_ws/src/ETIO/Trajactory/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                      # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ